### PR TITLE
New maintenance release fl1

### PR DESCRIPTION
**Pull request by nbenitez**
- Update runtime to 24.08
- Fix for #24
- Try to reduce app size
- Try to fix Aarch64 build
- Add caption to screenshots

### CODE REVIEW

**Comment by nbenitez** [comment]
bot, build com.github.ahrm.sioyek

**Comment by nbenitez** [comment]
bot, build com.github.ahrm.sioyek

**Comment by nbenitez** [comment]
bot, build com.github.ahrm.sioyek

**Comment by nbenitez** [comment]
bot, build com.github.ahrm.sioyek

**Comment by bbhtt** [comment]
Why did you not use `--persist`?

**Comment by nbenitez** [comment]
> Why did you not use `--persist`?

It didn't work, I tried both `--persist=.config` and `--persist=.config/sioyek` and the host's file `~/.config/sioyek/prefs_user.config` didn't appear inside the flatpak.

**Pull request merged**
