### PR TITLE
Add beta release for Sioyek github code at 23/03/2024

### PR DESCRIPTION
**Pull request by nbenitez**
So people can use latest Sioyek until there's a new release.

### CODE REVIEW

**Comment by Aman9das** [comment]
Kindly consider using Kde platform and removing the qt5 module to reduce app size..

Also what do the patches do?

**Comment by Aman9das** [comment]
The build is failing due to the patch. Does it not build without the patch?

**Comment by Aman9das** [comment]
Kindly remove c++ headers in /include to reduce app size too..

**Comment by nbenitez** [comment]
> Kindly remove c++ headers in /include to reduce app size too..

Thanks for such good tip, that's great reduce in size, I've added it! 🙂

**Comment by Aman9das** [comment]
#17 
Screenshot from 2024-04-07 19-56-10

#18 
Screenshot from 2024-04-07 19-47-38

I'm on GNOME, and the builds from #17 have adwaita header with `QT_QPA_PLATFORMTHEME=adwaita`, but this one I'm unable to make use of adwaita headers..
Why is unable to theme the window controls

**Pull request merged**
