### PR TITLE
Update runtime to 23.08

### PR DESCRIPTION
**Pull request by applemayexist**
~Assuming there isn't a reason Qt is built specifically for this package.~
(edit) [There is!](https://github.com/flathub/com.github.ahrm.sioyek/pull/13#issuecomment-1712406964)

### CODE REVIEW

**Comment by nbenitez** [comment]
I'm sorry but yes, it was specifically built to avoid an unnecessary KDE runtime dep, this is appreciated more for people like me (and others) which use GNOME or other non-KDE desktop.

The other way around, KDE users do appreciate when GTK apps (which don't use GNOME features) are built just with the Freedesktop runtime.

**Comment by applemayexist** [comment]
Okay, thanks!

**Comment by SteveLauC** [comment]
Merge of this PR would close #14

**Comment by nbenitez** [comment]
Update to a new runtime version should be done in its own MR, not here.

**Pull request closed without merging**
